### ISSUE TITLE
setter 方法没有考虑 Memory-Management Semantics

### ISSUE THREAD

**Issue by bigyelow** [douban/Polymorph#7]
@crazytonyli  setter 方法需要区分 Memory-Management Semantics 吧？

https://github.com/douban/Polymorph/blob/master/Polymorph/Polymorph.m#L249

对于 copy 的属性需要使用 `OBJC_ASSOCIATION_COPY_NONATOMIC`
对于 assign 的属性需要使用 `OBJC_ASSOCIATION_ASSIGN`

**Comment by crazytonyli** [comment]
是的，应该像你说的这样。

**Comment by bigyelow** [comment]
好的，我回头提 pr
